model_name: gpt-4o-2024-08-06
cheap_model_name: gpt-4o-mini
temperature: 0
request_timeout: 120
google_calendar:
  scopes:
    - https://www.googleapis.com/auth/calendar
  credentials_file: 'credentials.json'
  token_file: 'token.json'